spring.application.name=game
spring.config.import=optional:file:.env[.properties]
spring.profiles.default=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT config shared by all profiles
security.jwt.secret=${JWT_SECRET_KEY}
security.jwt.expiration=${JWT_EXP_TIME}









