package com.example.game.enums;

public enum EventType {
    AIR_TRAFFIC_BUZZ,
    VC_FUNDING_OFFER,
    HACKATHON_NEARBY,
    TECH_RECRUITER,
    COFFEE_SHOP_DEAL,
    OPEN_SOURCE_DRAMA,
    HARDWARE_FAILURE,
    TEAM_MEMBER_QUITS,
    VIRAL_TWEET,
    WEATHER_SHIFT
}
